---
title: "Wine Club Stats"
output: html_document
date: "March 2017"
---

```{r setup, include=FALSE, echo=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(knitr)
```

## Ratings by person
```{r cars, echo=FALSE}
ratings <- read.csv('./data/ratings.csv', stringsAsFactors = FALSE)
overview <- read.csv('./data/overview.csv', stringsAsFactors = FALSE)
wines <- read.csv('./data/wines.csv', stringsAsFactors = FALSE)

fulldata <- ratings %>%
  inner_join(overview) %>%
  inner_join(wines)
```

```{r, echo=FALSE}
people_tbl <- ratings %>%
  group_by(Person) %>%
  summarise(avg_rating = mean(Rating, na.rm=TRUE), var_rating = sd(Rating, na.rm=TRUE)) %>%
  arrange(desc(avg_rating))

kable(people_tbl)
```

```{r, echo=FALSE}
best_ratings <- ratings %>%
  group_by(Person) %>%
  summarise(Rating = max(Rating, na.rm=TRUE))

best_wines <- ratings %>%
  inner_join(best_ratings, by=c('Person', 'Rating')) %>%
  inner_join(wines) %>%
  inner_join(overview) %>%
  select(Person, RedWhite, WineType, Rating, Winery) %>%
  arrange(Person, WineType)
kable(best_wines)
```

